apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30030
    - port: 50000
      name: agent
      targetPort: 50000
    # nodePort: 30033
