apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: kube-ops
spec:
  nfs:
    path: /opt/nfs/jenkins-data
    server: 192.168.6.188
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 10Gi
