apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    name: jenkins
  type: NodePort
  ports:
    - port: 80
      name: web
      targetPort: 8080
      protocol: TCP
      nodePort: 30030
    - port: 30033
      name: agent
      targetPort: 30033
      nodePort: 30033
